
#### REGISTER

POST http://localhost:6000/api/auth/register
content-type: application/json

{
  "firstname": "an",
  "lastname": "an",
  "username": "an",
  "password": "an"
}

### LOGIN

POST http://localhost:8000/api/auth/login
content-type: application/json

{
  "username": "an",
  "password": "an"
}

### CREATE A NEW VIDEO

POST http://localhost:5000/api/video/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5YzU5M2ZmZWM3ZTZmYjFlMDhlNTgiLCJpYXQiOjE2OTA5NDUwNzd9.9J7JW78ra8ZWo3v-ur9xil9lyuYbhod1NNC5HiwJKYY

{
  "video": "7.mp4",
  "language": "en",
  "noise": "deep",
  "summary": "kl",
  "sentence": 2
}

### Get Videos All

GET http://localhost:6000/api/video/getallvideo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5YzU5M2ZmZWM3ZTZmYjFlMDhlNTgiLCJpYXQiOjE2OTA5NDUwNzd9.9J7JW78ra8ZWo3v-ur9xil9lyuYbhod1NNC5HiwJKYY

### Get video details

GET http://localhost:6000/api/video/getvideodetail/20230730_083504
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM2MjBhMjY1ZjBlNzBlYWM0M2E0YTMiLCJpYXQiOjE2OTA3MDYwODJ9.du_spWg3xJlIpz_jDeHQd9Ij3r6Y1PITegQe5kAOsNg

### FLASK API TEST

POST http://localhost:5000/api/createSummarize
Content-Type: application/json

{
  "video": "7.mp4",
  "language": "vi",
  "noise": "noise",
  "summary": "textrank",
  "sentence": 2
}

