
#### REGISTER

POST http://localhost:6000/api/auth/register
content-type: application/json

{
  "firstname": "toan",
  "lastname": "do",
  "username": "toan",
  "password": "toan"
}

### LOGIN

POST http://localhost:6000/api/auth/login
content-type: application/json

{
  "username": "jim",
  "password": "jim"
}


### TEST SAVE VIDEO RESULTS

POST http://localhost:6000/api/video/save
content-type: application/json

{
  "textSummarization": "textrank",
  "noiseReduction": "no",
  "sentenceCountInput": 10,
  "wordCountInput": 200,
  "sentenceCountOutput": 5,
  "wordCountOutput": 100,
  "processing_time": 30,
  "rouge1": {
    "recall": 0.75,
    "precision": 0.80,
    "f1Score": 0.77
  },
  "rouge2": {
    "recall": 0.65,
    "precision": 0.70,
    "f1Score": 0.68
  },
  "rougel": {
    "recall": 0.80,
    "precision": 0.85,
    "f1Score": 0.82
  }
}

### API CREATE A NEW VIDEO

POST http://localhost:6000/api/video/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGMxMjMwNWE2YjhmMTViNTM1MmViZWEiLCJpYXQiOjE2OTA2OTgwNDR9.a__7bCt_FU-gkY57TNJm5_KTyWn-LDxIT4W9GKihYlw

{
  "video": "7.mp4",
  "language": "vi",
  "noise": "noise",
  "summary": "textrank",
  "sentence": 0
}

### FLASK API TEST

POST http://localhost:5000/api/createSummarize
Content-Type: application/json

{
  "video": "7.mp4",
  "language": "vi",
  "noise": "noise",
  "summary": "textrank",
  "sentence": 2
}


